apiVersion: v1
data:
  app-config.properties: |
    # 数据库地址
    postgres_host=pg-quant-invest
    postgres_port=5432
    postgres_user=user
    postgres_password=password
    postgres_database=market

    log_level=DEBUG
    log_output_path=/app/project_name/data/log/sys-app.log
    cache_folder=/app/project_name/data/cache/
kind: ConfigMap
metadata:
  name: project_name-main-config
  namespace: quant-invest
